on:
  push:
    branches:
      - main
  workflow_dispatch:

# only one workflow should run at a time for this repository
concurrency:
  group: ${{ github.repository_owner }}-${{ github.event.repository.name }}-job
  cancel-in-progress: false

jobs:
  sleep_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo identifier for concurrency
        run: echo "${{ github.repository_owner }}-${{ github.event.repository.name }}-job"


      - name: Sleep for 10 seconds
        run: |
          echo "Sleeping for 10 seconds..."
          sleep 10
          echo "Done sleeping!"

  sleep_job_2:
    runs-on: ubuntu-latest
    needs: sleep_job_1  # Ensure sleep_job_1 completes before starting sleep_job_2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sleep for 10 seconds
        run: |
          echo "Sleeping for 10 seconds..."
          sleep 10
          echo "Done sleeping!"

  sleep_job_3:
    runs-on: ubuntu-latest
    needs: sleep_job_2  # Ensure sleep_job_2 completes before starting sleep_job_3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sleep for 10 seconds
        run: |
          echo "Sleeping for 10 seconds..."
          sleep 10
          echo "Done sleeping!"
